<a href="https://colab.research.google.com/github/AbdulDD/Pytorch/blob/main/LeNet_5_on_MNIST_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LeNet - 5

*   In this notebook, we reproduce the 1998 [paper](https://leon.bottou.org/papers/lecun-98h) by Yann Lecun and his team.

*   We will implement LeNet-5 Architecture on MNIST dataset



*   The Architecture is added here for reference. It is from the same paper discussed above



![Image](https://drive.google.com/uc?export=view&id=1u8gMjW87FcVCvlD-rl5_UW9XtuFIXYVm)


In [ ]:
from torch.utils.data import TensorDataset, DataLoader

import torch
import torchvision
import torch.nn as nn

# Load Dataset

In [ ]:
import tensorflow as tf


# Load the MNIST dataset directly from keras datasets
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
# Check the dataset
print('------------------------------------------------')
print('Training dataset')
print(f'Shape of image samples: {x_train.shape}')
print(f'Shape of target samples: {y_train.shape}')
print('------------------------------------------------')
print('Testing dataset')
print(f'Shape of image samples: {x_test.shape}')
print(f'Shape of target samples: {y_test.shape}')

------------------------------------------------
Training dataset
Shape of image samples: (60000, 28, 28)
Shape of target samples: (60000,)
------------------------------------------------
Testing dataset
Shape of image samples: (10000, 28, 28)
Shape of target samples: (10000,)


In [ ]:
# Let's check smaples
y_test[5], y_train[4], y_test[67], y_train[976]

(np.uint8(1), np.uint8(9), np.uint8(4), np.uint8(8))

In [ ]:
x_test[5]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  77, 254, 107,   3,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  19, 227, 254, 254,   9,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  81, 254, 254, 165,   1,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   7, 203, 254, 254,  73,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  53, 254, 254, 250,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 134, 254, 254, 180,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 196, 254, 248,  48,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         58, 254, 254, 237,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        111, 254, 254, 132,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        163, 254, 238,  28,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  60,
        252, 254, 223,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  79,
        254, 254, 154,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 163,
        254, 238,  53,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  28, 252,
        254, 210,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  86, 254,
        254, 131,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 105, 254,
        234,  20,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 175, 254,
        204,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   5, 211, 254,
        196,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3, 158, 254,
        160,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

In [ ]:
x_test[765]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 105, 253, 188,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 227, 252, 152,
          0,   0,   0,   0,   0,   0,   0,  36,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  98, 253, 245,  27,
          0,   0,   0,   0,   0,   6, 153, 242,  58,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 132, 253, 168,   0,
          0,   0,   0,   0,   0, 134, 252, 225,  21,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 211, 253,  80,   0,
          0,   0,   0,   0,  62, 239, 252, 124,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  38, 236, 254,  63,   0,
          0,   0,   0,   0, 189, 253, 236,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  64, 252, 253,  63,   0,
          0,   0,   0,   0, 232, 252, 147,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  64, 252, 250,  58,   0,
          0,   0,   0,  87, 251, 247,  47,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 134, 252, 211,   0,   0,
          0,   0,  29, 232, 252, 162,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 169, 252, 229,  27,   0,
          0,   0,  87, 252, 252,  84,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  54, 247, 254, 174,  51,
         43,  43, 210, 253, 236,  14,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 131, 253, 252, 252,
        252, 252, 253, 252, 201,  21,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   9,  83, 205, 242,
        252, 252, 253, 252,  29,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  42,
         84, 154, 253, 196,   7,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 194, 253, 124,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 212, 255,  63,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 211, 236,  37,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 202, 253,  72,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 106, 253, 168,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

# Pytorch Tensor conversion and Data Loader

In [ ]:
# Convert TensorFlow tensors to Pytorch Tensors

x_train = torch.tensor(x_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)



In [ ]:
# Check the dataset
print('------------------------------------------------')
print('Training dataset')
print(f'Shape of image samples: {x_train.shape}')
print(f'Shape of target samples: {y_train.shape}')
print('------------------------------------------------')
print('Testing dataset')
print(f'Shape of image samples: {x_test.shape}')
print(f'Shape of target samples: {y_test.shape}')

------------------------------------------------
Training dataset
Shape of image samples: torch.Size([60000, 28, 28])
Shape of target samples: torch.Size([60000])
------------------------------------------------
Testing dataset
Shape of image samples: torch.Size([10000, 28, 28])
Shape of target samples: torch.Size([10000])


In [ ]:
# Let's check smaples
y_test[5], y_train[4], y_test[67], y_train[976]

(tensor(1), tensor(9), tensor(4), tensor(8))

In [ ]:
x_test[765].shape

torch.Size([28, 28])

In [ ]:
x_train = x_train.unsqueeze(1)
x_test = x_test.unsqueeze(1)

In [ ]:
print(f'Training Images Shape: {x_train.shape}, Testing Images Shape: {x_test.shape}')

Training Images Shape: torch.Size([60000, 1, 28, 28]), Testing Images Shape: torch.Size([10000, 1, 28, 28])


In [ ]:
# Create Tensor Dataset
train_dataset = TensorDataset(x_train, y_train)
test_dataset = TensorDataset(x_test, y_test)

In [ ]:
image, label = train_dataset[7]
print(f'Tensor shape of image: {image.shape}, Tensor shape of label: {label.shape}')

Tensor shape of image: torch.Size([1, 28, 28]), Tensor shape of label: torch.Size([])


In [ ]:
# DataLoader
train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False
)

In [ ]:
for image, label in train_loader:
  print(label)
  break

tensor([0, 7, 5, 1, 7, 7, 6, 7, 2, 4, 2, 4, 3, 0, 9, 4, 3, 1, 5, 5, 9, 0, 6, 8,
        0, 8, 9, 1, 8, 7, 6, 2, 2, 2, 5, 0, 9, 0, 9, 9, 0, 7, 2, 5, 3, 4, 2, 4,
        1, 1, 1, 4, 6, 5, 4, 6, 2, 5, 5, 4, 7, 6, 0, 5])


# Architecture Design

In [ ]:
# Convolution Layer
CovLayer1 = nn.Conv2d(1, 5, 5)

#Pooling Layer
Poollayer1 = nn.MaxPool2d(2,2)

# ReLu
ReLU1 = nn.ReLU()

# Convolution Layer
CovLayer2 = nn.Conv2d(5, 16, 5)

# ReLu
ReLU2 = nn.ReLU()

#Pooling Layer
Poollayer2 = nn.MaxPool2d(2,2)


# Flatten Layer
Flattenlayer = nn.Flatten()

# Dense Layer
DenseLayer1 = nn.Linear(256, 64)

# ReLU3
ReLU3 = nn.ReLU()

# Dense Layer
DenseLayer2 = nn.Linear(64, 10)




In [ ]:
# Hyper parameters

# Loss Function
loss_fn = nn.CrossEntropyLoss()

# Epochs & Learning rate
Epochs = 10
lr = 0.01

# Optimizer
optimizer = torch.optim.Adam(
    [
        *CovLayer1.parameters(),
        *CovLayer2.parameters(),
        *DenseLayer1.parameters(),
        *DenseLayer2.parameters(),

    ],
    lr = lr
)



In [ ]:
# Not iterator/list but all elements (Example for understanding use of "*")
a = [1, 2]
b = [3, 4]

c = [*a, *b]

c

[1, 2, 3, 4]

# Training Custom LeNet-5 on MNIST Dataset

In [ ]:
# Training Loop

for epoch in range(Epochs):

  total_loss = 0

  for image, label in train_loader:


    # Forward Pass start
    # Convolution Block 1
    x = CovLayer1(image)
    x = ReLU1(x)
    x = Poollayer1(x)

    # Convolution Block 2
    x = CovLayer2(x)
    x = ReLU2(x)
    x = Poollayer2(x)

    # Flatten Layer
    x = Flattenlayer(x)

    # Dense Layer
    x = DenseLayer1(x)
    x = ReLU3(x)

    # Output Layer (Provides Logits)
    Logit = DenseLayer2(x)

    # Forward Pass Ends

    # Calculate Loss
    Loss = loss_fn(Logit, label)

    # Gradients to zero
    optimizer.zero_grad()

    # Backpropogation
    Loss.backward()

    # Update Weights
    optimizer.step()

    # Add batch loss
    total_loss += Loss.item()

  # Calculate epoch loss
  epoch_loss = total_loss/len(train_loader)

  # Print epoch loss
  print(f'Epoch: {epoch + 1}/{Epochs} ----> Loss: {epoch_loss:.4f}')









Epoch: 1/10 ----> Loss: 0.3683
Epoch: 2/10 ----> Loss: 0.2231
Epoch: 3/10 ----> Loss: 0.2204
Epoch: 4/10 ----> Loss: 0.2448
Epoch: 5/10 ----> Loss: 0.2489
Epoch: 6/10 ----> Loss: 0.2182
Epoch: 7/10 ----> Loss: 0.2847
Epoch: 8/10 ----> Loss: 0.2429
Epoch: 9/10 ----> Loss: 0.3237
Epoch: 10/10 ----> Loss: 0.3842


# Testing Accuracy