<a href="https://colab.research.google.com/github/AbdulDD/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
Tensors are the core data abstraction in PyTorch. They simplify complex numerical computations and manage hardware acceleration behind the scenes. This abstraction allows developers to focus on building the high-level logic of neural networks, while PyTorch efficiently handles the low-level execution of operations on the available hardware, such as CPUs or GPUs.

**Strengths of Tensors**
- Hardware Acceleration
- Automatic Differentiation
- Broadcasting
- Integration with Python

In this Notebook we will practice Tensor class of PyTorch.

In [2]:
# Imports
import torch
import math

## Creating tensors and random seeding

In [8]:
# create tensors

# empty tensor
emp = torch.empty(1, 4)
zeros_tensor = torch.zeros(2,2)

emp, zeros_tensor

(tensor([[ 3.3339e-14,  0.0000e+00, -4.0724e+15,  4.4923e-41]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [12]:
'''
manual_seed is usedd to create a reproducable tensor
'''

# Initialize random weights with seed
seed = torch.manual_seed(1729)
weights = torch.rand(4,4)
print(weights)


print('--------------------------------------')

# Update the weights
weights = weights + 3
print(weights)

print('--------------------------------------')

# Re-Initialize the weights with seed
seed = torch.manual_seed(1729)
weights = torch.rand(4,4)
print(weights)


tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453, 0.5035]])
--------------------------------------
tensor([[3.3126, 3.3791, 3.3087, 3.0736],
        [3.4216, 3.0691, 3.2332, 3.4047],
        [3.2162, 3.9927, 3.4128, 3.5938],
        [3.6128, 3.1519, 3.0453, 3.5035]])
--------------------------------------
tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938],
        [0.6128, 0.1519, 0.0453, 0.5035]])


In [22]:
# Create Tensors directly

'''
torch.tensor takes one argument
ARGUMENT:
1. list
2. tuple
3. list of lists/tuples
4. tuple of lists/tuples
5. tuple/list of hubird e.g torch.tensor(([1,2,4,5], (1,4,2,3)))

NOTE: for case 3,4,5 dimensions of all elements (lists/tuples) in tensor must be same
'''

w = torch.tensor([1,3,4,5,6])
x = torch.tensor([[1,3,5,7], [2,4,6,8]])
y = torch.tensor(((12,45,67,23,23),(1,2,3,4,4)))
z = torch.tensor(([1,2,4,5], (1,4,2,3)))

## Tensors shapes
- creating tensors with same dimension as we have in our input is possible with underscre ('torch.*_like(input)')

In [21]:
# input
x = torch.empty(2, 4,  4)

# create tensor with ones of shape same as x
y = torch.ones_like(x)

# Check the shapes
x.shape, y.shape

(torch.Size([2, 4, 4]), torch.Size([2, 4, 4]))

## Data types of tensor

In [29]:
# check data types of tensors
w.dtype, z.dtype


# setting data type at creation time for tensors
filter_data = torch.ones((3,4), dtype=torch.float32)
print(filter_data.dtype)

torch.float32


## Alter and Clone tensors



In [35]:
'''
Alter
to alter a tensor directly in memory (efficient memory use) we use ('_')
Example:
'''

# No change since we did not changed it in memory
a = torch.tensor([1,2,4])
b = a

a = a*4

print(a)
print(b)

# change it in memory
a = torch.tensor([1,2,4])
b = a

a = a.mul_(4)

print(a)
print(b)

tensor([ 4,  8, 16])
tensor([1, 2, 4])
tensor([ 4,  8, 16])
tensor([ 4,  8, 16])


In [40]:
'''
Clone

- By assigning a tensor to a variable (a,b,c,...) we set a new label for same tensor,
- the tensor is not copied. To copy a tensor we have to clone() it.
'''
# create a tensor
x = torch.ones(2,2)

# assign it to other variable
y = x

# clone it
z = x.clone()

# perform multiplication operation on x
x.mul_(2)

# check now
print(x)
print(y)
print(z)



tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])


## squeeze() and unsqueeze()
- PyTorch takes input in batches an therefore tensors normally have an extra dimension added that is batch.
- Therefore if we are working with single sample we have to use squeeze() that removes batch dimension
- On otherhand unsqueeze() adds an extent dmension of 1
- squeeze() and unsequeeze only works with one dimension

In [43]:
'''
- squeeze() removes batch dimension
'''
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([1, 20])
tensor([[0.7220, 0.8217, 0.2612, 0.7375, 0.8328, 0.8444, 0.2941, 0.3788, 0.4567,
         0.0649, 0.6677, 0.7826, 0.1332, 0.0023, 0.4945, 0.3857, 0.9883, 0.4762,
         0.7242, 0.0776]])
torch.Size([20])
tensor([0.7220, 0.8217, 0.2612, 0.7375, 0.8328, 0.8444, 0.2941, 0.3788, 0.4567,
        0.0649, 0.6677, 0.7826, 0.1332, 0.0023, 0.4945, 0.3857, 0.9883, 0.4762,
        0.7242, 0.0776])


In [44]:
'''
- squeeze() and unsequeeze() only works with one dimension
'''
c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [45]:
'''
- unsqueeze() adds batch dimension
'''
a = torch.rand(2,3,3)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([2, 3, 3])
torch.Size([1, 2, 3, 3])


## AutoGrad and detach()
- Autograd calculates the gradients after backpropogation directly
- detach removes the gradients history from tensor (As in C tensor)

In [48]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

print('---------------------------------------')
b = a.clone()
print(b)

print('---------------------------------------')
c = a.detach().clone()
print(c)


tensor([[0.1973, 0.3285],
        [0.5655, 0.0065]], requires_grad=True)
---------------------------------------
tensor([[0.1973, 0.3285],
        [0.5655, 0.0065]], grad_fn=<CloneBackward0>)
---------------------------------------
tensor([[0.1973, 0.3285],
        [0.5655, 0.0065]])
